import { StyleSheet } from "react-native";
import { WayperTheme } from "../../theme/wayperTheme";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: WayperTheme.colors.background },
  map: { flex: 1 },
  loading: { flex: 1, justifyContent: "center", alignItems: "center", padding: 20, backgroundColor: WayperTheme.colors.background },
  mapBottomFade: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 270,
  },
  mapTopVignette: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    height: 120,
  },
  recoveryBanner: {
    position: "absolute",
    left: 18,
    right: 18,
    top: 18,
    minHeight: 44,
    borderRadius: WayperTheme.radius.pill,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(8, 16, 24, 0.9)",
    borderWidth: 1,
    borderColor: WayperTheme.colors.primaryBorder,
  },
  recoveryBannerText: {
    flex: 1,
    color: WayperTheme.colors.text,
    fontSize: 12,
    fontWeight: "800",
  },
  territoryLoadingBadge: {
    position: "absolute",
    top: 18,
    right: 18,
    width: 42,
    height: 42,
    borderRadius: WayperTheme.radius.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(8, 16, 24, 0.86)",
    borderWidth: 1,
    borderColor: WayperTheme.colors.primaryBorder,
  },
  recenterMapButton: {
    position: "absolute",
    right: 22,
    bottom: 132,
    width: 58,
    height: 58,
    borderRadius: WayperTheme.radius.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(8, 16, 24, 0.9)",
    borderWidth: 1,
    borderColor: WayperTheme.colors.primaryBorder,
    overflow: "hidden",
    ...WayperTheme.shadows.card,
  },
  recenterMapGlow: {
    position: "absolute",
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: WayperTheme.colors.primarySoft,
    opacity: 0.82,
  },

  runPanel: {
    position: "absolute",
    top: 18,
    left: 18,
    right: 18,
    zIndex: 30,
    elevation: 30,
    padding: 15,
    borderRadius: WayperTheme.radius.xxl,
    backgroundColor: "rgba(8, 16, 24, 0.86)",
    borderWidth: 1,
    borderColor: WayperTheme.colors.primaryBorder,
    ...WayperTheme.shadows.card,
    overflow: "hidden",
  },
  runPanelPaused: {
    borderColor: "rgba(255, 204, 51, 0.36)",
    backgroundColor: "rgba(11, 20, 29, 0.9)",
  },
  runPanelGlow: {
    position: "absolute",
    top: -28,
    left: 42,
    right: 42,
    height: 70,
    borderRadius: 70,
    backgroundColor: WayperTheme.colors.primarySoft,
    opacity: 0.72,
  },
  runHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 13,
    gap: 10,
  },
  runTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  runEyebrow: {
    color: WayperTheme.colors.primary,
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1.2,
    textTransform: "uppercase",
    marginBottom: 2,
  },
  runTitle: {
    ...WayperTheme.typography.subtitle,
    letterSpacing: 0.2,
  },
  runStatusActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
    flexShrink: 0,
  },
  emergencyDiagnosticsButton: {
    minHeight: 34,
    paddingHorizontal: 10,
    borderRadius: WayperTheme.radius.pill,
    backgroundColor: "rgba(16, 27, 37, 0.94)",
    borderWidth: 1,
    borderColor: WayperTheme.colors.borderStrong,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  emergencyDiagnosticsButtonBusy: {
    opacity: 0.82,
  },
  emergencyDiagnosticsText: {
    color: WayperTheme.colors.text,
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  runStatusPill: {
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: WayperTheme.radius.pill,
    backgroundColor: WayperTheme.colors.primarySoft,
    borderWidth: 1,
    borderColor: WayperTheme.colors.primaryBorder,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  runStatusPillPaused: {
    backgroundColor: "rgba(255, 204, 51, 0.13)",
    borderColor: "rgba(255, 204, 51, 0.36)",
  },
  runStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: WayperTheme.colors.primary,
    shadowColor: WayperTheme.colors.primary,
    shadowOpacity: 0.8,
    shadowRadius: 8,
  },
  runStatusDotPaused: {
    backgroundColor: WayperTheme.colors.warning,
    shadowColor: WayperTheme.colors.warning,
  },
  runStatusText: {
    color: WayperTheme.colors.text,
    fontSize: 12,
    fontWeight: "900",
  },
  runMetricsRow: { flexDirection: "row", gap: 10 },
  runMetricCard: {
    flex: 1,
    minHeight: 82,
    borderRadius: WayperTheme.radius.xl,
    backgroundColor: "rgba(16, 27, 37, 0.88)",
    borderWidth: 1,
    borderColor: WayperTheme.colors.border,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
  },
  runMetricIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: WayperTheme.colors.primarySoft,
    borderWidth: 1,
    borderColor: WayperTheme.colors.primaryBorder,
    marginBottom: 5,
  },
  runRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 6 },
  runLabel: { color: WayperTheme.colors.textMuted, fontWeight: "800", fontSize: 12, textTransform: "uppercase" },
  runValue: { color: WayperTheme.colors.primary, fontWeight: "900", fontSize: 20, marginTop: 1 },
  pausedNotice: {
    marginTop: 12,
    minHeight: 38,
    borderRadius: WayperTheme.radius.pill,
    paddingHorizontal: 13,
    backgroundColor: "rgba(255, 204, 51, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(255, 204, 51, 0.24)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  pausedNoticeText: {
    color: WayperTheme.colors.textMuted,
    fontSize: 12,
    fontWeight: "800",
    flexShrink: 1,
    textAlign: "center",
  },
  gpsNotice: {
    marginTop: 10,
    minHeight: 38,
    borderRadius: WayperTheme.radius.pill,
    paddingHorizontal: 13,
    backgroundColor: WayperTheme.colors.warningSoft || "rgba(255, 204, 51, 0.1)",
    borderWidth: 1,
    borderColor: WayperTheme.colors.warningBorder || "rgba(255, 204, 51, 0.28)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  gpsNoticeText: {
    color: WayperTheme.colors.warning,
    fontSize: 12,
    fontWeight: "800",
    flexShrink: 1,
    textAlign: "center",
  },
});
