import { StyleSheet } from "react-native";
import { WayperTheme } from "../../theme/wayperTheme";

export default StyleSheet.create({
  modeOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.58)",
    justifyContent: "flex-end",
  },
  modeBox: {
    width: "100%",
    backgroundColor: "rgba(8, 16, 24, 0.97)",
    paddingHorizontal: 22,
    paddingTop: 14,
    paddingBottom: 22,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderWidth: 1,
    borderColor: WayperTheme.colors.borderStrong,
    shadowColor: WayperTheme.colors.primary,
    shadowOpacity: 0.18,
    shadowRadius: 26,
    shadowOffset: { width: 0, height: -10 },
    elevation: 16,
  },
  modeHandle: {
    alignSelf: "center",
    width: 48,
    height: 5,
    borderRadius: WayperTheme.radius.pill,
    backgroundColor: WayperTheme.colors.borderStrong,
    marginBottom: 18,
  },
  modeHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 18,
  },
  modeIconWrap: {
    width: 54,
    height: 54,
    borderRadius: 27,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: WayperTheme.colors.primarySoft,
    borderWidth: 1,
    borderColor: WayperTheme.colors.primaryBorder,
    marginRight: 14,
  },
  modeTitleWrap: {
    flex: 1,
  },
  modeEyebrow: {
    color: WayperTheme.colors.primary,
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 2,
  },
  modeTitle: {
    color: WayperTheme.colors.text,
    fontSize: 24,
    fontWeight: "900",
  },
  modeOption: {
    minHeight: 82,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: WayperTheme.colors.primary,
    borderWidth: 1,
    borderColor: WayperTheme.colors.primaryLight,
    marginBottom: 12,
    shadowColor: WayperTheme.colors.primary,
    shadowOpacity: 0.28,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 0 },
    elevation: 10,
  },
  modeOptionDisabled: {
    opacity: 0.62,
  },
  modeOptionSecondary: {
    backgroundColor: WayperTheme.colors.surfaceSoft,
    borderColor: WayperTheme.colors.primaryBorder,
    shadowOpacity: 0.08,
  },
  modeOptionSecondaryTitle: {
    color: WayperTheme.colors.text,
  },
  modeOptionSecondarySubtitle: {
    color: WayperTheme.colors.textMuted,
  },
  modeOptionIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(3,16,9,0.18)",
    marginRight: 14,
  },
  modeOptionIconSecondary: {
    backgroundColor: WayperTheme.colors.primarySoft,
    borderWidth: 1,
    borderColor: WayperTheme.colors.primaryBorder,
  },
  modeOptionTextWrap: {
    flex: 1,
  },
  modeOptionTitle: {
    color: WayperTheme.colors.textInverse,
    fontSize: 17,
    fontWeight: "900",
  },
  modeOptionSubtitle: {
    color: "rgba(3, 16, 9, 0.72)",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 3,
  },
  cancelBtn: {
    minHeight: 48,
    backgroundColor: WayperTheme.colors.dangerSoft,
    borderRadius: WayperTheme.radius.pill,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 4,
    borderWidth: 1,
    borderColor: WayperTheme.colors.dangerBorder,
  },
  cancelBtnText: { color: WayperTheme.colors.text, fontWeight: "900", fontSize: 15 },

  modalContainer: { flex: 1, backgroundColor: "rgba(0,0,0,0.66)", justifyContent: "center", padding: 20 },
  permissionOverlay: {
    flex: 1,
    justifyContent: "center",
    padding: WayperTheme.spacing.xl,
    backgroundColor: "rgba(0,0,0,0.66)",
  },
  permissionNoticeModal: {
    width: "100%",
  },
  modalContent: { backgroundColor: WayperTheme.colors.surfaceElevated, borderRadius: WayperTheme.radius.xl, padding: 20, height: "80%", borderWidth: 1, borderColor: WayperTheme.colors.borderStrong },
  modalTitle: { ...WayperTheme.typography.title, marginBottom: 12 },
  runItem: { paddingVertical: 14, borderBottomWidth: 1, borderColor: WayperTheme.colors.border },
  runDate: { color: WayperTheme.colors.text, fontSize: 16, fontWeight: "700" },
  runStats: { color: WayperTheme.colors.textMuted, fontSize: 13, marginTop: 2 },
  closeBtn: { backgroundColor: WayperTheme.colors.surfaceSoft, paddingVertical: 14, borderRadius: WayperTheme.radius.pill, marginTop: 18, borderWidth: 1, borderColor: WayperTheme.colors.border },
  closeBtnText: { color: WayperTheme.colors.text, fontWeight: "700", textAlign: "center" },
  zonesPanelOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.62)",
  },
  zonesPanel: {
    width: "100%",
    maxHeight: "78%",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: "rgba(8, 16, 24, 0.98)",
    borderWidth: 1,
    borderColor: WayperTheme.colors.borderStrong,
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 16,
  },
  zonesPanelHandle: {
    width: 48,
    height: 5,
    borderRadius: WayperTheme.radius.pill,
    backgroundColor: WayperTheme.colors.borderStrong,
    alignSelf: "center",
    marginBottom: 14,
  },
  zonesPanelHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  zonesPanelEyebrow: {
    color: WayperTheme.colors.primary,
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  zonesPanelTitle: {
    color: WayperTheme.colors.text,
    fontSize: 24,
    fontWeight: "900",
  },
  zonesPanelClose: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: WayperTheme.colors.surfaceSoft,
    borderWidth: 1,
    borderColor: WayperTheme.colors.border,
  },
  zonesTabs: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 12,
  },
  zonesTab: {
    flex: 1,
    minHeight: 42,
    borderRadius: WayperTheme.radius.pill,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 5,
    backgroundColor: WayperTheme.colors.surfaceSoft,
    borderWidth: 1,
    borderColor: WayperTheme.colors.border,
    paddingHorizontal: 8,
  },
  zonesTabActive: {
    backgroundColor: WayperTheme.colors.primary,
    borderColor: WayperTheme.colors.primaryLight,
  },
  zonesTabText: {
    flexShrink: 1,
    color: WayperTheme.colors.textMuted,
    fontSize: 11,
    fontWeight: "900",
  },
  zonesTabTextActive: {
    color: WayperTheme.colors.textInverse,
  },
  zonesList: {
    maxHeight: 430,
  },
  zonesLoading: {
    minHeight: 160,
    alignItems: "center",
    justifyContent: "center",
  },
  zonesEmpty: {
    color: WayperTheme.colors.textMuted,
    textAlign: "center",
    fontWeight: "800",
    paddingVertical: 36,
  },
  zonesSummary: {
    color: WayperTheme.colors.primary,
    fontWeight: "900",
    marginBottom: 8,
  },
  zoneRow: {
    minHeight: 64,
    borderRadius: WayperTheme.radius.lg,
    borderWidth: 1,
    borderColor: WayperTheme.colors.border,
    backgroundColor: WayperTheme.colors.surfaceSoft,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    marginBottom: 9,
    gap: 10,
  },
  zoneColorDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.7)",
  },
  zoneRankBadge: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: WayperTheme.colors.primary,
  },
  zoneRankText: {
    color: WayperTheme.colors.textInverse,
    fontSize: 13,
    fontWeight: "900",
  },
  zoneRowBody: {
    flex: 1,
  },
  zoneRowTitle: {
    color: WayperTheme.colors.text,
    fontSize: 15,
    fontWeight: "900",
  },
  zoneRowMeta: {
    color: WayperTheme.colors.textMuted,
    fontSize: 12,
    fontWeight: "800",
    marginTop: 2,
  },
});
