import { WAYPER_FALLBACK_COORD } from "../../components/Map/WayperMapLibre";
import { projectMapCamera } from "./mapCameraProjection.js";
import {
  formatMapArea,
  formatMapDate,
  partitionTerritories,
  projectSavedRun,
  projectVisibleMapZones,
} from "./mapScreenViewProjection.js";

export function buildMapScreenModels({
  actions,
  currentUserId,
  lifecycle,
  liveRoutePath,
  liveRouteSegments,
  operations,
  presentation,
  replay,
  resources,
  run,
  saveRunSummary,
  territory,
}) {
  const camera = projectMapCamera({
    location: lifecycle.location,
    fallbackLocation: WAYPER_FALLBACK_COORD,
    replayPath: replay.replayPath,
    replaying: replay.replaying,
    running: run.running,
    paused: run.paused,
    mapFollowEnabled: presentation.mapFollowEnabled,
    mapFocusCenter: territory.mapFocusCenter,
  });
  const visibleMapZones = projectVisibleMapZones({
    showZones: true,
    running: run.running,
    mode: run.mode,
    polygons: lifecycle.polygons,
    showRunModal: run.showRunModal,
    showSavedModal: run.showSavedModal,
    completedZonePreview: run.completedZonePreview,
  });
  const { mine: myTerritories, others: otherTerritories } = partitionTerritories(
    territory.territories,
    currentUserId
  );
  const savedRun = projectSavedRun(run.lastSavedRun);

  return {
    canvasModel: {
      camera,
      map: {
        routePath: liveRoutePath,
        routeSegments: liveRouteSegments,
        replayPath: replay.replayPath,
        replaySegments: replay.replaySegments,
        zones: visibleMapZones,
        currentUserId,
        replaying: replay.replaying,
        running: run.running,
        recenterSignal: presentation.mapRecenterSignal,
        onUserInteraction: presentation.handleMapUserInteraction,
      },
      recovery: {
        noticeVisible: operations.noticeVisible,
        modalVisible: operations.modalVisible,
        pending: operations.pending,
        loading: operations.actionLoading,
        onContinue: operations.onContinue,
        onFinish: operations.onFinish,
        onDiscard: operations.onDiscard,
      },
      territory: {
        items: territory.territories,
        leaderCells: territory.leaderCells,
        selected: territory.selectedTerritory,
        loading: territory.territoryLoading,
        onPress: territory.handleTerritoryPress,
        onLeaderCellPress: territory.handleLeaderCellPress,
        onViewportChange: territory.handleTerritoryViewportChange,
      },
      onRecenter: presentation.recenterMapOnUser,
    },
    runControlsModel: {
      running: run.running,
      replaying: replay.replaying,
      paused: run.paused,
      mode: run.mode,
      timeSec: run.timeSec,
      distanceState: run.distanceState,
      gpsQualityWarning: run.gpsQualityWarning,
      emergencyDiagnosticsLoading: resources.loading,
      onDiagnosticsPress: resources.onPress,
      onDiagnosticsLongPress: resources.onLongPress,
      runtimeRecovering: resources.runtimeRecovering,
      isFinishingRun: run.isFinishingRun,
      permissionDenied: lifecycle.permissionDenied,
      locationPermission: lifecycle.locationPermission,
      onRequestLocation: lifecycle.requestMapLocationPermission,
      startAuraOpacity: presentation.startAuraOpacity,
      startPulseScale: presentation.startPulseScale,
      startPressAnim: presentation.startPressAnim,
      startPulseAnim: presentation.startPulseAnim,
      isRunStartBusy: operations.isRunStartBusy,
      openStartModal: actions.openStartModal,
      onStartPressIn: presentation.handleStartPressIn,
      onStartPressOut: presentation.handleStartPressOut,
      isStartingRun: operations.isStartingRun,
      counting: operations.counting,
      openZonesPanel: territory.openZonesPanel,
      pauseRun: operations.pauseRun,
      resumeRun: operations.resumeRun,
      stopRun: operations.stopRun,
      replaySpeedOptions: replay.replaySpeedOptions,
      replaySpeed: replay.replaySpeed,
      setReplayPlaybackSpeed: replay.setReplayPlaybackSpeed,
      stopReplay: replay.stopReplay,
    },
    territoryPanelsModel: {
      showRunsModal: run.showRunsModal,
      closeRunsModal: actions.closeRunsModal,
      runsList: lifecycle.runsList,
      openRunDetails: actions.openRunDetails,
      zonesPanelVisible: territory.zonesPanelVisible,
      closeZonesPanel: territory.closeZonesPanel,
      zonesPanelTab: territory.zonesPanelTab,
      selectZonesPanelTab: territory.selectZonesPanelTab,
      zonesPanelLoading: territory.zonesPanelLoading,
      zonesRanking: territory.zonesRanking,
      selectedRankingUser: territory.selectedRankingUser,
      formatArea: formatMapArea,
      loadRankingUserZones: territory.loadRankingUserZones,
      myTerritories,
      otherTerritories,
      focusTerritoryOnMap: territory.focusTerritoryOnMap,
      formatDate: formatMapDate,
    },
    savedRunDialogsModel: {
      visible: run.showSavedModal,
      closeSaved: () => {
        run.setShowSavedModal(false);
        run.setSavedShareVisible(false);
        run.setCompletedZonePreview([]);
      },
      savedRunTitle: savedRun.savedTitle,
      savedRunName: savedRun.name,
      savedRunDistance: savedRun.distance,
      savedRunDuration: savedRun.duration,
      savedRunIsZone: savedRun.isZone,
      savedZoneArea: savedRun.area,
      savedRunDate: savedRun.date,
      goToDetail: actions.goToSavedRunDetail,
      replaySavedRun: actions.replaySavedRun,
      openShare: () => run.setSavedShareVisible(true),
      shareTitle: savedRun.shareTitle,
      shareVisible: run.savedShareVisible,
      closeShare: () => run.setSavedShareVisible(false),
      lastSavedRun: run.lastSavedRun,
      sharePath: savedRun.path,
      runSegments: savedRun.segments,
      zoneCoords: savedRun.zoneCoords,
      fullCardTitle: savedRun.displayTitle,
      shareSubtitle: savedRun.shareSubtitle,
      savedRunPace: savedRun.pace,
      selectedTerritory: territory.selectedTerritory,
      selectedLeaderboard: territory.selectedTerritoryLeaderboard,
      currentUserId,
      closeTerritory: territory.closeSelectedTerritory,
      runFromTerritory: actions.runFromSelectedTerritory,
      openTerritoryRanking: actions.openSelectedTerritoryRanking,
      summaryVisible: run.showRunModal,
    },
    runDialogsModel: {
      summaryVisible: run.showRunModal,
      currentRunData: run.currentRunData,
      captureResult: run.captureResult,
      closeSummary: () => run.setShowRunModal(false),
      saveRunSummary,
      selectModeVisible: run.selectModeVisible,
      isRunStartBusy: operations.isRunStartBusy,
      closeMode: () => run.setSelectModeVisible(false),
      startWithCountdown: operations.startWithCountdown,
      permissionVisible: run.runPermissionNoticeVisible,
      closePermission: () => run.setRunPermissionNoticeVisible(false),
      locationPermission: lifecycle.locationPermission,
      requestLocation: resources.requestRequiredLocationPermission,
      limitationNotice: run.runLimitationNotice,
      closeLimitation: () => run.setRunLimitationNotice(null),
      requestLimitation: resources.requestRunLimitationPermission,
      counting: operations.counting,
      countdown: operations.countdown,
      startAuraOpacity: presentation.startAuraOpacity,
      startPulseScale: presentation.startPulseScale,
    },
  };
}

export default buildMapScreenModels;
