import { StyleSheet } from "react-native";
import { WayperTheme } from "../../theme/wayperTheme";

export default StyleSheet.create({
  menuPanel: {
    position: "absolute",
    bottom: 34,
    left: 28,
    right: 28,
    padding: 16,
    borderRadius: WayperTheme.radius.xxl,
    backgroundColor: "rgba(11, 20, 29, 0.74)",
    borderColor: WayperTheme.colors.borderStrong,
    borderWidth: 1,
    shadowColor: WayperTheme.colors.primary,
    shadowOpacity: 0.14,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 0 },
    ...WayperTheme.shadows.card,
  },
  menuTopGlow: {
    position: "absolute",
    top: -1,
    left: "42%",
    right: "42%",
    height: 2,
    borderRadius: WayperTheme.radius.pill,
    backgroundColor: WayperTheme.colors.primaryLight,
    shadowColor: WayperTheme.colors.primary,
    shadowOpacity: 0.9,
    shadowRadius: 10,
    elevation: 8,
  },
  mapPermissionNotice: {
    marginBottom: WayperTheme.spacing.md,
  },
  startButtonAura: {
    position: "absolute",
    left: 22,
    right: 22,
    top: 22,
    bottom: 22,
    borderRadius: WayperTheme.radius.pill,
    backgroundColor: WayperTheme.colors.primary,
  },
  startMainBtn: {
    width: "100%",
    minHeight: 72,
    paddingVertical: 19,
    borderRadius: WayperTheme.radius.pill,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    backgroundColor: WayperTheme.colors.primary,
    borderWidth: 1,
    borderColor: WayperTheme.colors.primaryLight,
    shadowColor: WayperTheme.colors.primary,
    shadowOpacity: 0.52,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 0 },
    ...WayperTheme.shadows.greenGlow,
  },
  startMainBtnDisabled: {
    opacity: 0.76,
  },
  startMainBtnHighlight: {
    position: "absolute",
    top: -26,
    bottom: -26,
    width: 86,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.20)",
  },
  startMainBtnGloss: {
    position: "absolute",
    left: 24,
    right: 24,
    top: 8,
    height: 20,
    borderRadius: WayperTheme.radius.pill,
    backgroundColor: "rgba(255,255,255,0.14)",
  },
  startMainBtnContent: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
  },
  startMainBtnTxt: { color: WayperTheme.colors.textInverse, fontSize: 22, fontWeight: "900" },
  startChevronCircle: {
    position: "absolute",
    right: 28,
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(3,16,9,0.18)",
  },
  viewZonesButton: {
    minHeight: 52,
    marginTop: 12,
    borderRadius: WayperTheme.radius.pill,
    backgroundColor: WayperTheme.colors.surfaceGlass,
    borderWidth: 1,
    borderColor: WayperTheme.colors.primaryBorder,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  viewZonesButtonText: {
    color: WayperTheme.colors.text,
    fontSize: 15,
    fontWeight: "900",
  },

  bottomButtons: { position: "absolute", bottom: 28, left: 22, right: 22, alignItems: "stretch" },
  replayDock: {
    position: "absolute",
    bottom: 28,
    left: 22,
    right: 22,
    zIndex: 25,
    elevation: 25,
    borderRadius: WayperTheme.radius.xxl,
    padding: 10,
    backgroundColor: "rgba(8, 16, 24, 0.9)",
    borderWidth: 1,
    borderColor: WayperTheme.colors.borderStrong,
    gap: 10,
    overflow: "hidden",
    ...WayperTheme.shadows.card,
  },
  replaySpeedRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  replaySpeedButton: {
    flex: 1,
    height: 40,
    borderRadius: WayperTheme.radius.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: WayperTheme.colors.surfaceSoft,
    borderWidth: 1,
    borderColor: WayperTheme.colors.border,
  },
  replaySpeedButtonActive: {
    backgroundColor: WayperTheme.colors.primary,
    borderColor: WayperTheme.colors.primaryLight,
    ...WayperTheme.shadows.greenGlow,
  },
  replaySpeedText: {
    color: WayperTheme.colors.textMuted,
    fontSize: 14,
    fontWeight: "900",
  },
  replaySpeedTextActive: {
    color: WayperTheme.colors.textInverse,
  },
  bottomAction: { width: "100%" },
  runActionDock: {
    position: "absolute",
    bottom: 28,
    left: 22,
    right: 22,
    zIndex: 30,
    elevation: 30,
    minHeight: 86,
    borderRadius: WayperTheme.radius.xxl,
    padding: 10,
    backgroundColor: "rgba(8, 16, 24, 0.84)",
    borderWidth: 1,
    borderColor: WayperTheme.colors.borderStrong,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    overflow: "hidden",
    ...WayperTheme.shadows.card,
  },
  runActionDockGlow: {
    position: "absolute",
    top: -1,
    left: "38%",
    right: "38%",
    height: 2,
    borderRadius: WayperTheme.radius.pill,
    backgroundColor: WayperTheme.colors.primaryLight,
    shadowColor: WayperTheme.colors.primary,
    shadowOpacity: 0.9,
    shadowRadius: 12,
  },
  runControlButton: {
    flex: 1,
    minHeight: 62,
    borderRadius: WayperTheme.radius.pill,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 9,
    borderWidth: 1,
  },
  pauseControlButton: {
    backgroundColor: WayperTheme.colors.surfaceSoft,
    borderColor: WayperTheme.colors.primaryBorder,
  },
  resumeControlButton: {
    backgroundColor: WayperTheme.colors.primary,
    borderColor: WayperTheme.colors.primaryLight,
    ...WayperTheme.shadows.greenGlow,
  },
  finishControlButton: {
    backgroundColor: WayperTheme.colors.danger,
    borderColor: WayperTheme.colors.dangerBorder,
    ...WayperTheme.shadows.dangerGlow,
  },
  runControlText: {
    color: WayperTheme.colors.text,
    fontSize: 16,
    fontWeight: "900",
  },
  resumeControlText: {
    color: WayperTheme.colors.textInverse,
  },
  finishControlText: {
    color: WayperTheme.colors.text,
  },
});
