import { StyleSheet } from "react-native";
import { WayperTheme } from "../../theme/wayperTheme";

export default StyleSheet.create({
  savedOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.72)",
  },
  savedModalContent: {
    width: "100%",
    maxHeight: "92%",
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
    alignSelf: "center",
    backgroundColor: "rgba(8, 16, 24, 0.97)",
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    borderWidth: 1,
    borderColor: WayperTheme.colors.borderStrong,
    shadowColor: WayperTheme.colors.primary,
    shadowOpacity: 0.18,
    shadowRadius: 26,
    shadowOffset: { width: 0, height: -10 },
    elevation: 18,
    overflow: "hidden",
  },
  savedModalScroller: {
    flexGrow: 0,
  },
  savedModalScrollContent: {
    paddingBottom: 22,
  },
  savedHandle: {
    width: 48,
    height: 5,
    borderRadius: WayperTheme.radius.pill,
    backgroundColor: WayperTheme.colors.borderStrong,
    alignSelf: "center",
    marginBottom: 18,
  },
  savedHeroRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 15,
  },
  savedBadgeOuter: {
    width: 76,
    height: 76,
    borderRadius: 38,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: WayperTheme.colors.primarySoft,
    borderWidth: 1,
    borderColor: WayperTheme.colors.primaryBorder,
    ...WayperTheme.shadows.greenGlow,
  },
  savedBadgeInner: {
    width: 54,
    height: 54,
    borderRadius: 27,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: WayperTheme.colors.primary,
  },
  savedHeroText: {
    flex: 1,
  },
  savedEyebrow: {
    color: WayperTheme.colors.primary,
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1.1,
    textTransform: "uppercase",
  },
  savedTitle: {
    color: WayperTheme.colors.text,
    fontSize: 27,
    fontWeight: "900",
    marginTop: 2,
  },
  savedSubtitle: {
    color: WayperTheme.colors.textMuted,
    fontSize: 14,
    fontWeight: "700",
    marginTop: 3,
  },
  savedMetricRow: {
    flexDirection: "row",
    gap: 9,
    marginTop: 18,
  },
  savedMetric: {
    flex: 1,
    minHeight: 78,
    borderRadius: WayperTheme.radius.xl,
    backgroundColor: WayperTheme.colors.surfaceSoft,
    borderWidth: 1,
    borderColor: WayperTheme.colors.border,
    padding: 10,
    justifyContent: "center",
  },
  savedMetricValue: {
    color: WayperTheme.colors.text,
    fontSize: 14,
    fontWeight: "900",
    marginTop: 5,
  },
  savedMetricLabel: {
    color: WayperTheme.colors.textSubtle,
    fontSize: 11,
    fontWeight: "800",
    marginTop: 1,
  },
  savedPrimaryAction: {
    minHeight: 58,
    marginTop: 18,
    borderRadius: WayperTheme.radius.pill,
    backgroundColor: WayperTheme.colors.primary,
    borderWidth: 1,
    borderColor: WayperTheme.colors.primaryLight,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    ...WayperTheme.shadows.greenGlow,
  },
  savedPrimaryText: {
    color: WayperTheme.colors.textInverse,
    fontSize: 16,
    fontWeight: "900",
  },
  savedSecondaryAction: {
    minHeight: 54,
    marginTop: 10,
    borderRadius: WayperTheme.radius.pill,
    backgroundColor: WayperTheme.colors.surfaceSoft,
    borderWidth: 1,
    borderColor: WayperTheme.colors.primaryBorder,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
  },
  savedSecondaryText: {
    color: WayperTheme.colors.text,
    fontSize: 15,
    fontWeight: "900",
  },
  savedCloseAction: {
    minHeight: 50,
    marginTop: 12,
    borderRadius: WayperTheme.radius.pill,
    backgroundColor: WayperTheme.colors.surfaceSoft,
    borderWidth: 1,
    borderColor: WayperTheme.colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  savedCloseText: {
    color: WayperTheme.colors.text,
    fontSize: 15,
    fontWeight: "900",
  },
  countdownOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  countdownBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  countdownAura: {
    position: "absolute",
    width: 310,
    height: 310,
    borderRadius: 155,
    backgroundColor: WayperTheme.colors.primary,
    shadowColor: WayperTheme.colors.primary,
    shadowOpacity: 0.55,
    shadowRadius: 42,
    shadowOffset: { width: 0, height: 0 },
    elevation: 18,
  },
  countdownBox: {
    width: 282,
    height: 282,
    borderRadius: 141,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(8, 16, 24, 0.78)",
    borderColor: WayperTheme.colors.primaryBorder,
    borderWidth: 1,
    overflow: "hidden",
  },
  countdownRingOuter: {
    width: 242,
    height: 242,
    borderRadius: 121,
    borderWidth: 2,
    borderColor: WayperTheme.colors.primary,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: WayperTheme.colors.primarySoft,
    shadowColor: WayperTheme.colors.primary,
    shadowOpacity: 0.5,
    shadowRadius: 24,
  },
  countdownRingMiddle: {
    width: 202,
    height: 202,
    borderRadius: 101,
    borderWidth: 1,
    borderColor: WayperTheme.colors.primaryBorder,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(3, 7, 11, 0.76)",
  },
  countdownRingInner: {
    width: 164,
    height: 164,
    borderRadius: 82,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: WayperTheme.colors.surfaceGlass,
    borderWidth: 1,
    borderColor: WayperTheme.colors.borderStrong,
  },
  countdownLabel: {
    color: WayperTheme.colors.textMuted,
    fontSize: 13,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: -4,
  },
  countdownNumber: {
    fontSize: 76,
    fontWeight: "900",
    color: WayperTheme.colors.primary,
    textShadowColor: WayperTheme.colors.primaryGlow,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 22,
  },
  countdownHint: {
    color: WayperTheme.colors.textMuted,
    fontSize: 12,
    fontWeight: "800",
    marginTop: -4,
  },
});
